
@host = http://localhost:8080

POST http://localhost:8080/api/v1/users/sign-in
Content-Type: application/json

{
  "username": "asdf123",
  "password": "asdfgA12@"
}
> {%
  client.global.set("access_token", response.headers.valueOf("Authorization"))
%}

### 👩🏻‍💻 Hub 테이블 더미데이터에 필요한 코드
###
### - 서울특별시 센터 : 서울특별시 송파구 송파대로 55
POST http://localhost:8080/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "name": "서울특별시 센터",
  "address": "서울특별시 송파구 송파대로 55"
}

### - 경기 북부 센터 : 경기도 고양시 덕양구 권율대로 570
POST http://localhost:8080/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "name": "경기 북부 센터",
  "address": "경기도 고양시 덕양구 권율대로 570"
}

### - 경기 남부 센터 : 경기도 이천시 덕평로 257-21
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "경기 남부 센터",
  "address": "경기도 이천시 덕평로 257-21"
}

### - 부산광역시 센터 : 부산 동구 중앙대로 206
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "부산광역시 센터",
  "address": "부산 동구 중앙대로 206"
}

### - 대구광역시 센터 : 대구 북구 태평로 161
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "대구광역시 센터",
  "address": "대구 북구 태평로 161"
}

### - 인천광역시 센터 : 인천 남동구 정각로 29
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "인천광역시 센터",
  "address": "인천 남동구 정각로 29"
}

### - 광주광역시 센터 : 광주 서구 내방로 111
POST{{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "광주광역시 센터",
  "address": "광주 서구 내방로 111"
}

### - 대전광역시 센터 : 대전 서구 둔산로 100
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "대전광역시 센터",
  "address": "대전 서구 둔산로 100"
}

### - 울산광역시 센터 : 울산 남구 중앙로 201
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "울산광역시 센터",
  "address": "울산 남구 중앙로 201"
}

### - 세종특별자치시 센터 : 세종특별자치시 한누리대로 2130
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "세종특별자치시 센터",
  "address": "세종특별자치시 한누리대로 2130"
}

### - 강원특별자치도 센터 : 강원특별자치도 춘천시 중앙로 1
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "강원특별자치도 센터",
  "address": "강원특별자치도 춘천시 중앙로 1"
}

### - 충청북도 센터 : 충북 청주시 상당구 상당로 82
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "충청북도 센터",
  "address": "충북 청주시 상당구 상당로 82"
}

### - 충청남도 센터 : 충남 홍성군 홍북읍 충남대로 21
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "충청남도 센터",
  "address": "충남 홍성군 홍북읍 충남대로 21"
}

### - 전북특별자치도 센터 : 전북특별자치도 전주시 완산구 효자로 225
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "전북특별자치도 센터",
  "address": "전북특별자치도 전주시 완산구 효자로 225"
}

### - 전라남도 센터 : 전남 무안군 삼향읍 오룡길 1
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "전라남도 센터",
  "address": "전남 무안군 삼향읍 오룡길 1"
}

### - 경상북도 센터 : 경북 안동시 풍천면 도청대로 455
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "경상북도 센터",
  "address": "경북 안동시 풍천면 도청대로 455"
}

### - 경상남도 센터 : 경남 창원시 의창구 중앙대로 300
POST {{host}}/api/v1/hubs
Content-Type: application/json
Authorization:  {{access_token}}

{
  "name": "경상남도 센터",
  "address": "경남 창원시 의창구 중앙대로 300"
}