POST http://localhost:8080/api/v1/users/sign-up
Content-Type: application/json

{
    "username":"asdf123",
    "password":"asdfgA12@",
    "email":"asdf@naver.com",
    "slackName": "asdggg"
}

###

POST http://localhost:8080/api/v1/users/sign-in
Content-Type: application/json

{
  "username": "asdf123",
  "password": "asdfgA12@"
}

###

PUT http://localhost:8080/api/v1/users/update
Content-Type: application/json
Authorization: 로그인하고 생성된 토큰 넣어주세요!

{
  "username": "afdsjhsd24",
  "password": "asdfgA12gg@",
  "email":"asdfg3@naver.com",
  "slackName": "asdgggh"
}