### 상품 생성
POST http://localhost:8083/api/v1/products
Content-Type: application/json
X-User-Id: 12345  # 사용자 ID (Long 타입)

{
  "name": "마른오징어3",
  "description": "마른오징어 입니다3.",
  "price": 1000,
  "quantity": 50,
  "isDisplay": true,
  "companyId": "550e8400-e29b-41d4-a716-446655440000",
  "hubId": "123e4567-e89b-12d3-a456-426614174000"
}


### 상품 단일 조회
GET http://localhost:8083/api/v1/products/a8fe0567-e857-4427-a612-555328391a36
Content-Type: application/json


### 상품 목록 조회
GET http://localhost:8083/api/v1/products
Content-Type: application/json


### 상품 수정
PUT http://localhost:8083/api/v1/products/69e23662-9e36-4172-96db-8003308fcb45
Content-Type: application/json

{
  "name": "마른오징어 수정",
  "description": "마른오징어 입니다 수정.",
  "price": 3000,
  "isDisplay": false
}
