### 상품 생성
POST http://localhost:8083/api/v1/products
Content-Type: application/json
X-User-Id: 12345  # 사용자 ID (Long 타입)

{
  "name": "마른오징어3",
  "description": "마른오징어 입니다3.",
  "price": 1000,
  "quantity": 50,
  "isDisplay": true,
  "companyId": "550e8400-e29b-41d4-a716-446655440000",
  "hubId": "123e4567-e89b-12d3-a456-426614174000"
}


### 상품 단일 조회
GET http://localhost:8083/api/v1/products/a8fe0567-e857-4427-a612-555328391a36
Content-Type: application/json


### 상품 목록 조회
GET http://localhost:8083/api/v1/products
Content-Type: application/json


### 상품 수정
PUT http://localhost:8083/api/v1/products/69e23662-9e36-4172-96db-8003308fcb45
Content-Type: application/json

{
  "name": "마른오징어 수정",
  "description": "마른오징어 입니다 수정.",
  "price": 3000,
  "isDisplay": false
}


### 상품 수정(재고 감소 성공)
PUT http://localhost:8083/api/v1/products/d6183a42-df2e-44fa-8331-cf7a90a1f82e/decrease
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoiMSIsInJvbGUiOiJST0xFX01BU1RFUiIsInNsYWNrX25hbWUiOiJhc2RnZ2ciLCJpc3MiOiJ1c2VyLXNlcnZpY2UiLCJpYXQiOjE3NDI3ODg3OTEsImV4cCI6MTc0Mjc5MjM5MX0.GTMZCuZ7-jfzYshDEfBdCAfelNFAexIogXxU6rzX3fNTaeQ0GPFilKyylO_E90PiX5DFUWBQ29oIChuMpUU-gg
Content-Type: application/json

{
  "companyId": "550e8400-e29b-41d4-a716-446655440000",
  "hubId": "123e4567-e89b-12d3-a456-426614174000",
  "quantity": 30
}


### 상품 수정(재고 감소 실패)
PUT http://localhost:8083/api/v1/products/fabd981b-844a-47f9-a15c-60ae362c2eb7/decrease
Content-Type: application/json

{
  "companyId": "550e8400-e29b-41d4-a716-446655440000",
  "hubId": "123e4567-e89b-12d3-a456-426614174000",
  "quantity": 100
}


### 상품 수정(재고 증가)
PUT http://localhost:8080/api/v1/products/d6183a42-df2e-44fa-8331-cf7a90a1f82e/increase
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoiMSIsInJvbGUiOiJST0xFX01BU1RFUiIsInNsYWNrX25hbWUiOiJhc2RnZ2ciLCJpc3MiOiJ1c2VyLXNlcnZpY2UiLCJpYXQiOjE3NDI3ODg3OTEsImV4cCI6MTc0Mjc5MjM5MX0.GTMZCuZ7-jfzYshDEfBdCAfelNFAexIogXxU6rzX3fNTaeQ0GPFilKyylO_E90PiX5DFUWBQ29oIChuMpUU-gg
Content-Type: application/json

{
  "companyId": "550e8400-e29b-41d4-a716-446655440000",
  "hubId": "123e4567-e89b-12d3-a456-426614174000",
  "quantity": 30
}


### 상품 삭제
DELETE http://localhost:8083/api/v1/products/225dc81a-7b96-4905-83b9-16945fef9a7d
X-User-Id: 12345  # 사용자 ID (Long 타입)




### 상품 검색 (상품 이름으로 검색)
GET http://localhost:8083/api/v1/products/search?name=치킨&page=0&size=10&sort=createdAt,asc


### 상품 검색 (상품 설명으로 검색)
GET http://localhost:8083/api/v1/products/search?description=치킨 입니다&page=0&size=10&sort=createdAt,asc


### 상품 검색 (허브 ID로 검색)
GET http://localhost:8083/api/v1/products/search?hubId=123e4567-e89b-12d3-a456-426614174002&page=0&size=10&sort=createdAt,asc


### 상품 검색 (업체 ID로 검색)
GET http://localhost:8083/api/v1/products/search?companyId=550e8400-e29b-41d4-a716-446655440001&page=0&size=10&sort=createdAt,asc





