server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:  # Spring Cloud Gateway? ??? ??
        - id: user-service  # ??? ???
          uri: lb://user-service  # 'user-service'?? ???? ?? ???? ???? ???
          predicates:
            - Path=/api/v1/users/**       # /api/v1/users/** ??? ???? ??? ? ???? ??
        - id: order-service
          uri: lb://order-service
          predicates:
           - Path=/api/v1/orders/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/api/v1/auth/**
      discovery:
        locator:
          enabled: true  # ??? ?????? ?? ???? ???? ????? ??

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#service:
#  jwt:
#    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
