spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://localhost:5432/company-service
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true  # 실행되는 SQL 쿼리 출력
      database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /company-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8085
