spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5001/maindb
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: user_service
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: false  # H2 콘솔 비활성화 (PostgreSQL 사용 시)
server:
  port: 8081

eureka:
  client:
    register-with-eureka: true # Eureka? ??? ??
    fetch-registry: true # Eureka?? ??? ?? ????
    service-url:
      defaultZone: http://localhost:8761/eureka/

service:
  jwt:
    access-expiration: 3600000 # 1시간 뒤 만료
    secret-key: "50OsBNAaYDd8KJkGL8DCy8l8GFeJY--lzgxXrQJA-vUl1ZfivKtLNuwR_qNn2LJ6NkXpg8AAa2fe2CVUtN4UcQ"
  master:
    signup-key: "mgbE4vogtrMGufz6PXkQNTV-KZtU4-Mz7_wcKf7r40kKTu8z4BD9l_kacdd4MzU3pQV6y3LB-yrmMvvXFKep2Q"
  hub:
    signup-key: "WS4LLkUhglcrzhFaqWhGXMX70V-ntoQrJdsbT8997aR32veCI2Y35-yyjdHzUzVc4TybaGSdRJ6WYVVcY9K6Uw"
  shipping:
    signup-key: "QqjxcIpIisVqc2evLWPRyjMya8nCyWiheO5L8SbxwKbJFRjlIkxFaX1l8ShI8GlE1hxw_oOoyrfefEE7ZrUkMQ"


springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /user-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html