spring:
  application:
    name: user-service

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true # Eureka? ??? ??
    fetch-registry: true # Eureka?? ??? ?? ????
  service-url:
    defaultZone: http://localhost:8761/eureka/
