spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5001/maindb
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: order_service
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /order-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8084
