
ext {
    set('springCloudVersion', "2024.0.0")
}

dependencies {
    // 공통 모듈
    implementation project(':common-module')
    // eureka client
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    // 유효성 검사
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // Spring Boot 및 JPA 관련 의존성
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'

    // JGraphT : 그래프 자료구조 및 알고리즘 제공
    implementation 'org.jgrapht:jgrapht-core:1.5.1'

    // QueryDSL
    implementation 'com.querydsl:querydsl-jpa:5.1.0:jakarta'
    annotationProcessor 'com.querydsl:querydsl-apt:5.1.0:jakarta'
    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'

    implementation 'org.hibernate:hibernate-core:6.3.1.Final' // Hibernate ORM 라이브러리
    implementation("org.postgresql:postgresql:42.7.2") // PostgreSQL JDBC 드라이버
    runtimeOnly 'com.h2database:h2' // 개발/테스트 환경에서 H2 사용
}

// ✅ QueryDSL 자동 생성 디렉토리 설정
tasks.withType(JavaCompile).configureEach {
    options.annotationProcessorGeneratedSourcesDirectory = file("$buildDir/generated/querydsl")
}

// ✅ 자동 생성된 QueryDSL 클래스 경로 추가
sourceSets {
    main {
        java {
            srcDirs += "$buildDir/generated/querydsl"
        }
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}